version: '3.8'

services:
  nuxt:
    container_name: nuxt
    build:
      dockerfile: ci/Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
      - "${HMR_PORT}:24678"
    volumes:
      - ./:/nuxt
    env_file:
      - ./.env
    command: pnpm dev